<?php

use Illuminate\Database\Seeder;
use App\Institucion;

class InstitucionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Institucion::create(array('nombre_institucion' => 'Agencia de Regulación y Control de la Bioseguridad y Cuarentena para Galápagos','siglas_institucion' => 'ABG'));
		Institucion::create(array('nombre_institucion' => 'Agencia de Aseguramiento de la Calidad de los Servicios de Salud y Medicina Prepagada AGR','siglas_institucion' => 'ACESS'));
		Institucion::create(array('nombre_institucion' => 'Agencia de Regulación y Control Fito y Zoosanitario – AGROCALIDAD','siglas_institucion' => 'AGR'));
		Institucion::create(array('nombre_institucion' => 'Empresa Pública Municipal de Agua Potable y Alcantarillado de Chone','siglas_institucion' => 'AGUASCHUNO'));
		Institucion::create(array('nombre_institucion' => 'Asociación de Municipalidades Ecuatorianas','siglas_institucion' => 'AME'));
		Institucion::create(array('nombre_institucion' => 'Agencia Nacional de Regulación y Control de Transporte Terrestre, Tránsito y Seguridad Vial','siglas_institucion' => 'ANT'));
		Institucion::create(array('nombre_institucion' => 'Autoridad Portuaria de Esmeraldas','siglas_institucion' => 'APE'));
		Institucion::create(array('nombre_institucion' => 'Autoridad Portuaria de Guayaquil','siglas_institucion' => ' APG'));
		Institucion::create(array('nombre_institucion' => 'Autoridad Portuaria de Manta','siglas_institucion' => 'APM'));
		Institucion::create(array('nombre_institucion' => 'Autoridad Portuaria de Puerto Bolívar','siglas_institucion' => 'APPB'));
		Institucion::create(array('nombre_institucion' => 'Agencia de Regulación y Control del Agua','siglas_institucion' => 'ARCA'));
		Institucion::create(array('nombre_institucion' => 'Agencia de Regulación y Control Minero','siglas_institucion' => 'ARCOM'));
		Institucion::create(array('nombre_institucion' => 'Agencia de Regulación y Control de Electricidad','siglas_institucion' => 'ARCONEL'));
		Institucion::create(array('nombre_institucion' => 'Agencia de Regulación y Control de las Telecomunicaciones','siglas_institucion' => 'ARCOTEL'));
		Institucion::create(array('nombre_institucion' => 'Agencia de Regulación y Control Postal','siglas_institucion' => 'ARCP'));
		Institucion::create(array('nombre_institucion' => 'Agencia Nacional de Regulación, Control y Vigilancia Sanitaria','siglas_institucion' => 'ARCSA'));
		Institucion::create(array('nombre_institucion' => 'Agencia de Regulación y Control Hidrocarburífero','siglas_institucion' => 'ARCH'));
		Institucion::create(array('nombre_institucion' => 'Fuerza Naval','siglas_institucion' => 'ARE'));
		Institucion::create(array('nombre_institucion' => 'Astilleros Navales Ecuatorianos','siglas_institucion' => 'ASTINAVEEP'));
		Institucion::create(array('nombre_institucion' => 'Autoridad de Tránsito Mancomunada Centro Guayas','siglas_institucion' => 'ATMCG'));
		Institucion::create(array('nombre_institucion' => 'BANECUADOR B.P.','siglas_institucion' => 'BANECUADOR'));
		Institucion::create(array('nombre_institucion' => 'Banco Central del Ecuador','siglas_institucion' => 'BCE'));
		Institucion::create(array('nombre_institucion' => 'Banco de Desarrollo del Ecuador','siglas_institucion' => 'BDE'));
		Institucion::create(array('nombre_institucion' => 'Banco Ecuatoriano de la Vivienda en liquidación','siglas_institucion' => 'BEVLIQ'));
		Institucion::create(array('nombre_institucion' => 'Banco del Instituto Ecuatoriano de Seguridad Social','siglas_institucion' => 'BIESS'));
		Institucion::create(array('nombre_institucion' => 'Banco Nacional de Fomento en Liquidación','siglas_institucion' => 'BNF'));
		Institucion::create(array('nombre_institucion' => 'Cuerpo de Bomberos de Baños de Agua Santa','siglas_institucion' => 'C.B.B.'));
		Institucion::create(array('nombre_institucion' => 'Cuerpo de Bomberos del Cantón Cascales','siglas_institucion' => 'CBCC'));
		Institucion::create(array('nombre_institucion' => 'Cuerpo de Bomberos de Cayambe','siglas_institucion' => 'CBC'));
		Institucion::create(array('nombre_institucion' => 'Cuerpo de Bomberos del Distrito Metropolitano de Quito','siglas_institucion' => 'CBDMQ'));
		Institucion::create(array('nombre_institucion' => 'Cuerpo de Bomberos del Cantón Francisco de Orellana','siglas_institucion' => 'CBFO'));
		Institucion::create(array('nombre_institucion' => 'Cuerpo de Bomberos Municipal de Babahoyo','siglas_institucion' => 'CBM-B'));
		Institucion::create(array('nombre_institucion' => 'Cuerpo de Bomberos Pedro Moncayo','siglas_institucion' => 'CBPM'));
		Institucion::create(array('nombre_institucion' => 'Cuerpo de Bomberos de Salinas','siglas_institucion' => 'CBS'));
		Institucion::create(array('nombre_institucion' => 'Corporación Ciudad Alfaro','siglas_institucion' => 'CCA'));
		Institucion::create(array('nombre_institucion' => 'Casa de la Cultura Ecuatoriana Benjamín Carrión','siglas_institucion' => 'CCE'));
		Institucion::create(array('nombre_institucion' => 'Comando Conjunto','siglas_institucion' => 'CCFFAA'));
		Institucion::create(array('nombre_institucion' => 'Empresa Pública Correos del Ecuador','siglas_institucion' => 'CDE-EP'));
		Institucion::create(array('nombre_institucion' => 'Consejo de Evaluación, Acreditación y Aseguramiento de la Calidad de la Educación Superior','siglas_institucion' => 'CEAACES'));
		Institucion::create(array('nombre_institucion' => 'Centros de Entrenamiento para el Alto Rendimiento','siglas_institucion' => 'CEAREP'));
		Institucion::create(array('nombre_institucion' => 'Centro de Educación Continua','siglas_institucion' => 'CEC-EPN'));
		Institucion::create(array('nombre_institucion' => 'Empresa Pública Centro de Educación Continua','siglas_institucion' => 'EPN CEC-IAEN'));
		Institucion::create(array('nombre_institucion' => 'Corporación Eléctrica del Ecuador','siglas_institucion' => 'CELEC-EP'));
		Institucion::create(array('nombre_institucion' => 'Empresa Pública Coordinadora de Empresas Públicas Municipales de Antonio Ante','siglas_institucion' => 'CEMAA-EP'));
		Institucion::create(array('nombre_institucion' => 'Operador Nacional de Electricidad,','siglas_institucion' => 'CENACE'));
		Institucion::create(array('nombre_institucion' => 'Empresa Eléctrica Regional Centro Sur C.A.','siglas_institucion' => 'CENACE CENTROSUR'));
		Institucion::create(array('nombre_institucion' => 'Consejo de Educación Superior','siglas_institucion' => 'CES'));
		Institucion::create(array('nombre_institucion' => 'Corporación Financiera Nacional B.P.','siglas_institucion' => 'CFN'));
		Institucion::create(array('nombre_institucion' => 'Consejo De Gobierno De Galápagos','siglas_institucion' => 'CGREG'));
		Institucion::create(array('nombre_institucion' => 'Centro Interamericano de Artesanías y Artes Populares','siglas_institucion' => 'CIDAP'));
		Institucion::create(array('nombre_institucion' => 'Consejo Nacional de Competencias','siglas_institucion' => 'CNC'));
		Institucion::create(array('nombre_institucion' => 'Compañia Nacional de Danza','siglas_institucion' => 'CND'));
		Institucion::create(array('nombre_institucion' => 'Empresa Eléctrica Pública Estratégica Corporación Nacional de Electricidad CNEL EP','siglas_institucion' => 'CNEL'));
		Institucion::create(array('nombre_institucion' => 'Consejo Nacional para la Igualdad de Género','siglas_institucion' => 'CNIG'));
		Institucion::create(array('nombre_institucion' => 'Consejo Nacional para la Igualdad Intergeneracional','siglas_institucion' => 'CNII'));
		Institucion::create(array('nombre_institucion' => 'Consejo Nacional para la Igualdad de Movilidad Humana','siglas_institucion' => 'CNIMH'));
		Institucion::create(array('nombre_institucion' => 'Consejo Nacional para la Igualdad de Pueblos y Nacionalidades','siglas_institucion' => 'CNIPN'));
		Institucion::create(array('nombre_institucion' => 'Corporación Nacional de Telecomunicaciones','siglas_institucion' => 'CNT-EP'));
		Institucion::create(array('nombre_institucion' => 'Consejo Nacional para la Igualdad de Discapacidades','siglas_institucion' => 'CONADIS'));
		Institucion::create(array('nombre_institucion' => 'Corporación Nacional de Finanzas Populares y Solidarias','siglas_institucion' => 'CONAFIPS'));
		Institucion::create(array('nombre_institucion' => 'Consejo Nacional de Salud','siglas_institucion' => 'CONASA'));
		Institucion::create(array('nombre_institucion' => 'Conferencia Plurinacional e Intercultural de Soberanía Alimentaria','siglas_institucion' => 'COPISA'));
		Institucion::create(array('nombre_institucion' => 'Consejo de Regulación y Desarrollo de la Información y Comunicación','siglas_institucion' => 'CORDICOM'));
		Institucion::create(array('nombre_institucion' => 'Corporación del Seguro de Depósitos, Fondo de Liquidez y Fondo de Seguros Privados','siglas_institucion' => 'COSEDE'));
		Institucion::create(array('nombre_institucion' => 'Consejo de Participación Ciudadana y Control Social','siglas_institucion' => 'CPCCS'));
		Institucion::create(array('nombre_institucion' => 'Comisión de Tránsito del Ecuador','siglas_institucion' => 'CTE'));
		Institucion::create(array('nombre_institucion' => 'Dirección General de Aviación Civil','siglas_institucion' => 'DGAC'));
		Institucion::create(array('nombre_institucion' => 'Dirección General del Registro Civil, Identificación y Cedulación','siglas_institucion' => 'DIGERCIC'));
		Institucion::create(array('nombre_institucion' => 'Dirección Nacional de Registro de Datos Públicos','siglas_institucion' => 'DINARDAP'));
		Institucion::create(array('nombre_institucion' => 'Defensoría Pública','siglas_institucion' => 'DP'));
		Institucion::create(array('nombre_institucion' => 'Defensoría del Pueblo','siglas_institucion' => 'DPE'));
		Institucion::create(array('nombre_institucion' => 'Empresa de Agua Potable y Alcantarillado','siglas_institucion' => 'EAPASM'));
		Institucion::create(array('nombre_institucion' => 'San Mateo','siglas_institucion' => 'EAPA'));
		Institucion::create(array('nombre_institucion' => 'Instituto para el Ecodesarrollo Regional Amazónico','siglas_institucion' => 'ECORAE'));
		Institucion::create(array('nombre_institucion' => 'Empresa Eléctrica Azogues C.A.','siglas_institucion' => 'EEA'));
		Institucion::create(array('nombre_institucion' => 'Empresa Eléctrica Ambato Regional Centro Norte S.A.','siglas_institucion' => 'EEASA'));
		Institucion::create(array('nombre_institucion' => 'Ecuador Estratégico EP','siglas_institucion' => 'EEEP'));
		Institucion::create(array('nombre_institucion' => 'Electro Generadora del Austro S.A.','siglas_institucion' => 'EEGA'));
		Institucion::create(array('nombre_institucion' => 'Empresa Eléctrica Provincial Galápagos','siglas_institucion' => 'EEPGSA'));
		Institucion::create(array('nombre_institucion' => 'Empresa Eléctrica Quito','siglas_institucion' => 'EEQ'));
		Institucion::create(array('nombre_institucion' => 'Empresa Eléctrica Riobamba S.A.','siglas_institucion' => 'EERSA'));
		Institucion::create(array('nombre_institucion' => 'Empresa Eléctrica Regional del Sur','siglas_institucion' => 'EERSSA'));
		Institucion::create(array('nombre_institucion' => 'Fuerza Terrestre','siglas_institucion' => 'EJERCITO'));
		Institucion::create(array('nombre_institucion' => 'Empresa Eléctrica Provincial Cotopaxi S.A.','siglas_institucion' => 'ELEPCOSA'));
		Institucion::create(array('nombre_institucion' => 'Empresa Pública Municipal de Agua Potable y Alcantarillado de Daule','siglas_institucion' => 'EMAPAD'));
		Institucion::create(array('nombre_institucion' => 'Empresa Pública Municipal de Agua Potable y Alcantarillado de Durán','siglas_institucion' => 'EMAPAD-EP'));
		Institucion::create(array('nombre_institucion' => 'Empresa Municipal de Agua Potable, Alcantarillado y  Saneamiento de Gualaceo ','siglas_institucion' => 'EMAPAS-GEP'));
		Institucion::create(array('nombre_institucion' => 'Empresa Pública Municipal de Agua Potable y Alcantarillado de la Troncal','siglas_institucion' => 'EMAPATEP'));
		Institucion::create(array('nombre_institucion' => 'Empresa Coordinadora de Empresas Públicas','siglas_institucion' => 'EMCOEP'));
		Institucion::create(array('nombre_institucion' => 'Empresa Eléctrica Regional Norte','siglas_institucion' => 'EMELNORTE'));
		Institucion::create(array('nombre_institucion' => 'Empresa Pública Vial de Asfalto y Obras Civiles','siglas_institucion' => 'EMPROVIAL'));
		Institucion::create(array('nombre_institucion' => 'Empresa Nacional Minera','siglas_institucion' => 'ENAMI'));
		Institucion::create(array('nombre_institucion' => 'Empresa Pública de Fármacos','siglas_institucion' => 'ENFARMA EP'));
		Institucion::create(array('nombre_institucion' => 'Empresa Pública de Agua Potable y Alcantarillado de Antonio Ante','siglas_institucion' => 'EPAA-AA'));
		Institucion::create(array('nombre_institucion' => 'Empresa Pública del Agua','siglas_institucion' => 'EPA'));
		Institucion::create(array('nombre_institucion' => 'Empresa Pública Aguas de Manta','siglas_institucion' => 'EPAM'));
		Institucion::create(array('nombre_institucion' => 'Empresa Pública Cementera del Ecuador','siglas_institucion' => 'EPCE'));
		Institucion::create(array('nombre_institucion' => 'Empresa Pública Casa para Todos EP','siglas_institucion' => 'EPCPT'));
		Institucion::create(array('nombre_institucion' => 'Empresa Pública Municipal de Agua Potable y Alcantarillado y Saneamiento del cantón Calvas','siglas_institucion' => 'EP-EMAPAC'));
		Institucion::create(array('nombre_institucion' => 'Empresa Pública Municipal Mercado de Productores Agrícolas San Pedro de Riobamba','siglas_institucion' => 'EP-EMMPA'));
		Institucion::create(array('nombre_institucion' => 'IEmpresa Pública Fábrica Imbabura','siglas_institucion' => 'EPF'));
		Institucion::create(array('nombre_institucion' => 'Empresa Pública Municipal de Agua Potable y Alcantarillado de Latacunga','siglas_institucion' => 'EPMAPAL'));
		Institucion::create(array('nombre_institucion' => 'Empresa Pública Municipal de Agua Potable y Alcantarillado de Santo Domingo','siglas_institucion' => 'EPMAPA-SD'));
		Institucion::create(array('nombre_institucion' => 'Empresa Pública Municipal de Agua Potable y Alcantarillado Sanitario del cantón Jipijapa','siglas_institucion' => 'EPMAPAS-J'));
		Institucion::create(array('nombre_institucion' => 'Empresa Pública De Movilidad De La Mancomunidad De Cotopaxi','siglas_institucion' => 'EPMC'));
		Institucion::create(array('nombre_institucion' => 'Registro de la Propiedad del Cantón Santo Domingo','siglas_institucion' => 'EPMRPSD'));
		Institucion::create(array('nombre_institucion' => 'Empresa Pública Municipal de Tránsito de Guayaquil','siglas_institucion' => 'EPMTG'));
		Institucion::create(array('nombre_institucion' => 'Empresa Pública YACHAY E.P.','siglas_institucion' => 'EPYEP'));
		Institucion::create(array('nombre_institucion' => 'Empresa Pública Municipal de Telecomunicaciones, Agua Potable, Alcantarillado y Saneamiento  Cuenca','siglas_institucion' => 'ETAPA-EP'));
		Institucion::create(array('nombre_institucion' => 'Fuerza Aérea Ecuatoriana','siglas_institucion' => 'FA'));
		Institucion::create(array('nombre_institucion' => 'Ferrocarriles del Ecuador Empresa Pública','siglas_institucion' => 'FEEP'));
		Institucion::create(array('nombre_institucion' => 'Empresa Pública Flota Petrolera Ecuatoriana FLOPEC','siglas_institucion' => 'FLOPEC'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado  Municipal del cantón Baños de Agua Santa','siglas_institucion' => 'GADBAS'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Municipal del cantón Cumandá','siglas_institucion' => 'GADCC'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Municipal del Cantón Latacunga','siglas_institucion' => 'GADCL'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Municipal del Cantón Crnel. Marcelino Maridueña','siglas_institucion' => 'GAD-CMM-A'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Municipal del cantón Saquisilí','siglas_institucion' => 'GADCS'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Municipal del cantón Valencia','siglas_institucion' => 'GADCV'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Municipal del cantón Huaquillas','siglas_institucion' => 'GADH'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Intercultural del Cantón Cañar','siglas_institucion' => 'GADICC'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Municipal de San Miguel de Ibarra','siglas_institucion' => 'GADI'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Ilustre Municipalidad del Cantón Daule','siglas_institucion' => 'GADIMCD'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado  Municipal del cantón Jama','siglas_institucion' => 'GADJAMA'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Municipal del Cantón 24 de Mayo','siglas_institucion' => 'GADM24MAYO'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Municipal de Archidona','siglas_institucion' => 'GADMA'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Municipal del Cantón Ambato','siglas_institucion' => 'GADMA'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Municipal del cantón Aguarico','siglas_institucion' => 'GADMCA'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Municipal del cantón Baba','siglas_institucion' => 'GADMCB'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Municipal del cantón Chimbo','siglas_institucion' => 'GADMCCH'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Municipal del Cantón Durán','siglas_institucion' => 'GADMCD'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Municipal del Cantón El Empalme','siglas_institucion' => 'GADMCEE'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado  Municipal del cantón Cevallos','siglas_institucion' => 'GADMCEV'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado del Cantón Gualaceo','siglas_institucion' => 'GADMCG'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Municipal de Cascales','siglas_institucion' => 'GADMC'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Municipal del Cantón Gonzalo Pizarro','siglas_institucion' => 'GADMCGP'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Municipal del cantón Junín','siglas_institucion' => 'GADMCJ'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Municipal del cantón la Concordia','siglas_institucion' => 'GADMCLC'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Municipal del Cantón Manta','siglas_institucion' => 'GADMCMANTA'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado del  Cantón  Montalvo','siglas_institucion' => 'GADMCM'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Municipal del Cantón Mejía','siglas_institucion' => 'GADMCM'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Municipal del Cantón Naranjal','siglas_institucion' => 'GADMCN'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Municipal del Cantón Pedro Carbo','siglas_institucion' => 'GADMCPC'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Municipal del cantón Pastaza','siglas_institucion' => 'GADMCP'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Municipal del Cantón Puerto Quito','siglas_institucion' => 'GADMCPQ'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Municipal del Cantón Pedro Vicente Maldonado','siglas_institucion' => 'GADMCPVM'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Municipal Del Cantón Quevedo','siglas_institucion' => 'GADMCQ'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado  Municipal del cantón Quinindé','siglas_institucion' => 'GADMCQ'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Municipal del Cantón Rocafuerte','siglas_institucion' => 'GADMCR'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Municipal del cantón Sucre','siglas_institucion' => 'GADMCS'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Municipal de Chambo','siglas_institucion' => 'GADMCH'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Municipal de Girón','siglas_institucion' => 'GADMDG'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Municipal Francisco de Orellana','siglas_institucion' => 'GADMFO'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado del Cantón Mira','siglas_institucion' => 'GADMIRA'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Municipal de Lago Agrio','siglas_institucion' => 'GADMLA'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Municipal del cantón San Francisco de Milagro','siglas_institucion' => 'GADMM'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Municipal de Montúfar','siglas_institucion' => 'GADMM'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado  Municipal del cantón Oña','siglas_institucion' => 'GADMO'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Municipal de Pallatanga','siglas_institucion' => 'GADMP'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Municipal de Portovelo','siglas_institucion' => 'GADMP'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Municipal de Portoviejo','siglas_institucion' => 'GADMP'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Municipal de Pucará','siglas_institucion' => 'GADMP'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Municipal de Puyango','siglas_institucion' => 'GADMP'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Municipal del Cantón Putumayo','siglas_institucion' => 'GADMP'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Municipal del Cantón Puerto López','siglas_institucion' => 'GADMPL'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Municipal del cantón Riobamba','siglas_institucion' => 'GADMR'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado  Municipal de Santa Ana de Cotacachi','siglas_institucion' => 'GADMSAC'));
		Institucion::create(array('nombre_institucion' => 'Gobierno  Autónomo Descentralizado Municipal de Santa Cruz','siglas_institucion' => 'GADMSC'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado  Municipal San Cristobal de Patate','siglas_institucion' => 'GADMSCP'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Municipal de Santo Domingo','siglas_institucion' => 'GADMSD'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Municipal del cantón Salcedo','siglas_institucion' => 'GADMS'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Municipal de Sigchos','siglas_institucion' => 'GADMS'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Municipal de San Miguel de los Bancos','siglas_institucion' => 'GADMSMB'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Municipal San Pedro de Huaca','siglas_institucion' => 'GADMSPH'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Municipal del Cantón Santa Rosa','siglas_institucion' => 'GADMSR'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Municipal de Tena','siglas_institucion' => 'GADMT'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Municipal de San Miguel de Urcuquí','siglas_institucion' => 'GADMU'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Municipal de Pangua','siglas_institucion' => 'GADMUPAN'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Municipal del Cantón Vinces','siglas_institucion' => 'GADMVINCES'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Municipal de Zaruma','siglas_institucion' => 'GADMZ'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Parroquial  Rural de Cutuglagua','siglas_institucion' => 'GADPC'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Parroquial Rural de Conocoto','siglas_institucion' => 'GADPRC'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Parroquial Rural de Nuevo Quito','siglas_institucion' => 'GADPRNQ'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Parroquial Rural de Río Corrientes','siglas_institucion' => 'GADPRRC'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado  Parroquia Rural San Antonio de Pichincha','siglas_institucion' => 'GADPRSAP'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Provincial de Santa Elena','siglas_institucion' => 'GADPSE'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Municipal de Sígsig','siglas_institucion' => 'GADS-MS'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Cantonal de Pindal','siglas_institucion' => 'GCP'));
		Institucion::create(array('nombre_institucion' => 'Empresa Pública de Movilidad del Gobierno Autónomo Descentralizado Municipal del Cantón Gualaceo','siglas_institucion' => 'G-MOVEP'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Parroquial San Joaquín','siglas_institucion' => 'GPSJ'));
		Institucion::create(array('nombre_institucion' => 'Hospital de Especialidades Fuerzas Armadas N1','siglas_institucion' => 'HE-1'));
		Institucion::create(array('nombre_institucion' => 'Hidroeléctrica del Litoral HIDROLITORAL EP','siglas_institucion' => 'HLT EP'));
		Institucion::create(array('nombre_institucion' => 'Instituto Altos Estudios Nacionales','siglas_institucion' => 'IAEN'));
		Institucion::create(array('nombre_institucion' => 'Instituto de Cine y Creación Audiovisual','siglas_institucion' => 'ICCA'));
		Institucion::create(array('nombre_institucion' => 'Instituto Espacial Ecuatoriano','siglas_institucion' => 'IEE'));
		Institucion::create(array('nombre_institucion' => 'Instituto Ecuatoriano de Propiedad Intelectual','siglas_institucion' => 'IEPI'));
		Institucion::create(array('nombre_institucion' => 'Instituto Nacional de Economía Popular y Solidaria','siglas_institucion' => 'IEPS'));
		Institucion::create(array('nombre_institucion' => 'Instituto Ecuatoriano de Seguridad Social','siglas_institucion' => ' IESS'));
		Institucion::create(array('nombre_institucion' => 'Instituto de Fomento de las Artes, Innovación y Creatividades','siglas_institucion' => 'IFAIC'));
		Institucion::create(array('nombre_institucion' => 'Instituto de Fomento al Talento Humano','siglas_institucion' => 'IFTH'));
		Institucion::create(array('nombre_institucion' => 'Instituto Geográfico Militar','siglas_institucion' => 'IGM'));
		Institucion::create(array('nombre_institucion' => 'Instituto de Idiomas, Ciencias y Saberes Ancestrales','siglas_institucion' => 'IICSAE'));
		Institucion::create(array('nombre_institucion' => 'Empresa Pública Ikiam E.P.','siglas_institucion' => 'IKIAMEP'));
		Institucion::create(array('nombre_institucion' => 'Universidad Regional Amazónica  IKIAM','siglas_institucion' => 'IKIAM'));
		Institucion::create(array('nombre_institucion' => 'Instituto Nacional de Biodiversidad','siglas_institucion' => 'INABIO'));
		Institucion::create(array('nombre_institucion' => 'Instituto Antártico Ecuatoriano','siglas_institucion' => 'INAE'));
		Institucion::create(array('nombre_institucion' => 'Instituto Nacional de Meteorología e Hidrología','siglas_institucion' => 'INAMHI'));
		Institucion::create(array('nombre_institucion' => 'Instituto Nacional de Donación y Transplantes de Órganos Tejidos y Células','siglas_institucion' => 'INDOT'));
		Institucion::create(array('nombre_institucion' => 'Instituto Nacional de Estadística y Censos','siglas_institucion' => 'INEC'));
		Institucion::create(array('nombre_institucion' => 'Servicio Ecuatoriano de Normalización','siglas_institucion' => 'INEN'));
		Institucion::create(array('nombre_institucion' => 'Instituto Nacional de Eficiencia Energética y Energías Renovables','siglas_institucion' => 'INER'));
		Institucion::create(array('nombre_institucion' => 'Instituto Nacional de Evaluación Educativa','siglas_institucion' => 'INEVAL'));
		Institucion::create(array('nombre_institucion' => 'Instituto Nacional de Investigaciones Agropecuarias','siglas_institucion' => 'INIAP'));
		Institucion::create(array('nombre_institucion' => 'Instituto Nacional de Investigación Geológico Minero Metalúrgico','siglas_institucion' => 'INIGEMM'));
		Institucion::create(array('nombre_institucion' => 'Servicio de Gestión Inmobiliaria del Sector Público','siglas_institucion' => 'INMOBILIAR'));
		Institucion::create(array('nombre_institucion' => 'Instituto Oceanográfico de la Armada','siglas_institucion' => 'INOCAR'));
		Institucion::create(array('nombre_institucion' => 'Instituto Nacional de Patrimonio Cultural','siglas_institucion' => 'INPC'));
		Institucion::create(array('nombre_institucion' => 'Instituto Nacional de Investigación en Salud Pública  INSPI  Dr. Leopoldo Izquieta Pérez','siglas_institucion' => 'INSPI'));
		Institucion::create(array('nombre_institucion' => 'Instituto de Provisión de Alimentos','siglas_institucion' => 'IPA'));
		Institucion::create(array('nombre_institucion' => 'Infraestructuras Pesqueras del Ecuador, Empresa Pública','siglas_institucion' => 'IPEEP'));
		Institucion::create(array('nombre_institucion' => 'Sección Nacional del Instituto Panamericano de Geografía e Historia','siglas_institucion' => 'IPGH'));
		Institucion::create(array('nombre_institucion' => 'Instituto de Seguridad Social de las Fuerzas Armadas','siglas_institucion' => 'ISSFA'));
		Institucion::create(array('nombre_institucion' => 'Instituto Superior Tecnológico de Artes del Ecuador','siglas_institucion' => 'ITAE'));
		Institucion::create(array('nombre_institucion' => 'Junta Nacional de Defensa del Artesano','siglas_institucion' => 'JNDA'));
		Institucion::create(array('nombre_institucion' => 'Jefatura Provincial de Bomberos Loja JRHJunta de Recursos Hidráulicos y Obras Básicas','siglas_institucion' => 'JPBL'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autónomo Descentralizado Municipal de Antonio Ante','siglas_institucion' => 'MAA'));
		Institucion::create(array('nombre_institucion' => 'Ministerio del Ambiente','siglas_institucion' => 'MAE'));
		Institucion::create(array('nombre_institucion' => 'Ministerio de Coordinación de Conocimiento y Talento Humano','siglas_institucion' => 'MCCTH'));
		Institucion::create(array('nombre_institucion' => 'Ministerio de Comercio Exterior e Inversiones','siglas_institucion' => 'MCEI'));
		Institucion::create(array('nombre_institucion' => 'Ministerio de Coordinación de la Producción, Empleo y Competitividad','siglas_institucion' => 'MCPEC'));
		Institucion::create(array('nombre_institucion' => 'Ministerio de Cultura y Patrimonio','siglas_institucion' => 'MCYP'));
		Institucion::create(array('nombre_institucion' => 'Ministerio Del Interior','siglas_institucion' => 'MDI'));
		Institucion::create(array('nombre_institucion' => 'Ministerio del Deporte','siglas_institucion' => 'MD'));
		Institucion::create(array('nombre_institucion' => 'Ministerio de Defensa Nacional','siglas_institucion' => 'MDN'));
		Institucion::create(array('nombre_institucion' => 'Ministerio del Trabajo','siglas_institucion' => 'MDT'));
		Institucion::create(array('nombre_institucion' => 'Ministerio de Electricidad y Energía Renovable','siglas_institucion' => 'MEER'));
		Institucion::create(array('nombre_institucion' => 'Ministerio de Economía y Finanzas','siglas_institucion' => 'MEF'));
		Institucion::create(array('nombre_institucion' => 'Ministerio de Hidrocarburos','siglas_institucion' => 'MH'));
		Institucion::create(array('nombre_institucion' => 'Ministerio de Coordinación de Seguridad','siglas_institucion' => 'MICS'));
		Institucion::create(array('nombre_institucion' => 'Ministerio de Desarrollo Urbano y Vivienda','siglas_institucion' => 'MIDUVI'));
		Institucion::create(array('nombre_institucion' => 'Ministerio de Inclusión Económica y Social','siglas_institucion' => 'MIES'));
		Institucion::create(array('nombre_institucion' => 'Ministerio de Educación','siglas_institucion' => 'MINEDUC'));
		Institucion::create(array('nombre_institucion' => 'Ministerio de Telecomunicaciones y de la Sociedad de la Información','siglas_institucion' => 'MINTEL'));
		Institucion::create(array('nombre_institucion' => 'Ministerio de Justicia, Derechos Humanos y Cultos','siglas_institucion' => 'MJDHC'));
		Institucion::create(array('nombre_institucion' => 'Mancomunidad de Movilidad Centro Guayas','siglas_institucion' => 'MMCG'));
		Institucion::create(array('nombre_institucion' => 'Ministerio de Minería','siglas_institucion' => 'MM'));
		Institucion::create(array('nombre_institucion' => 'Empresa Pública Medios Públicos de Comunicación del Ecuador  Medios Públicos EP','siglas_institucion' => 'MPEP'));
		Institucion::create(array('nombre_institucion' => 'Ministerio de Relaciones Exteriores y Movilidad Humana','siglas_institucion' => 'MREMH'));
		Institucion::create(array('nombre_institucion' => 'Ministerio de Salud Pública','siglas_institucion' => 'MSP'));
		Institucion::create(array('nombre_institucion' => 'Ministerio de Turismo','siglas_institucion' => 'MT'));
		Institucion::create(array('nombre_institucion' => 'Ministerio de Transporte y Obras Públicas','siglas_institucion' => 'MTOP'));
		Institucion::create(array('nombre_institucion' => 'Mancomunidad de Tránsito de Sucumbíos EP','siglas_institucion' => 'MTS-EP'));
		Institucion::create(array('nombre_institucion' => 'Operaciones RIO NAPO Compañia de Economía Mixta','siglas_institucion' => 'ORNCEM'));
		Institucion::create(array('nombre_institucion' => 'Orquesta Sinfónica de Cuenca','siglas_institucion' => 'OSC'));
		Institucion::create(array('nombre_institucion' => 'Orquesta Sinfónica de Guayaquil','siglas_institucion' => 'OSG'));
		Institucion::create(array('nombre_institucion' => 'Orquesta Sinfónica Nacional del Ecuador','siglas_institucion' => 'OSNE'));
		Institucion::create(array('nombre_institucion' => 'Petroamazonas EP','siglas_institucion' => 'PAM'));
		Institucion::create(array('nombre_institucion' => 'Plan Binacional de Desarrollo de la Región Fronteriza','siglas_institucion' => 'PBDRF'));
		Institucion::create(array('nombre_institucion' => 'PetroEcuador','siglas_institucion' => 'PETRO'));
		Institucion::create(array('nombre_institucion' => 'Policía Nacional','siglas_institucion' => 'PN'));
		Institucion::create(array('nombre_institucion' => 'Patronato Provincial de Sucumbios','siglas_institucion' => 'PPASS'));
		Institucion::create(array('nombre_institucion' => 'Instituto de Promoción de Exportaciones e Inversiones Extranjeras PRO ECUADOR','siglas_institucion' => 'PROECU'));
		Institucion::create(array('nombre_institucion' => 'Presidencia de la República','siglas_institucion' => 'PR'));
		Institucion::create(array('nombre_institucion' => 'Empresa Pública Municipal de Pruebas','siglas_institucion' => 'PRUEBAS'));
		Institucion::create(array('nombre_institucion' => 'Refinería del Pacífico Eloy Alfaro','siglas_institucion' => 'RDP'));
		Institucion::create(array('nombre_institucion' => 'Revisión Técnica Vehicular RETEVE E.P.','siglas_institucion' => 'RETEVEE.P'));
		Institucion::create(array('nombre_institucion' => 'Registro Mercantil del cantón Esmeraldas','siglas_institucion' => 'RMCE'));
		Institucion::create(array('nombre_institucion' => 'Registro Mercantil del cantón Guayaquil','siglas_institucion' => 'RMCG'));
		Institucion::create(array('nombre_institucion' => 'Registro Mercantil del cantón Cuenca','siglas_institucion' => 'RMC'));
		Institucion::create(array('nombre_institucion' => 'Registro Mercantil del cantón Santo Domingo','siglas_institucion' => 'RMCSD'));
		Institucion::create(array('nombre_institucion' => 'Registro Municipal de la Propiedad y Mercantil del Cantón Playas','siglas_institucion' => 'RMPCP'));
		Institucion::create(array('nombre_institucion' => 'Registro Municipal de la Propiedad del Cantón Quevedo','siglas_institucion' => 'RMPQ'));
		Institucion::create(array('nombre_institucion' => 'Registro Mercantil del cantón Quito','siglas_institucion' => 'RMQ'));
		Institucion::create(array('nombre_institucion' => 'Registro de la Propiedad y Mercantil del cantón Biblián','siglas_institucion' => 'RPMCB'));
		Institucion::create(array('nombre_institucion' => 'Registro de la Propiedad y Mercantil del Cantón Pedro Moncayo','siglas_institucion' => 'RPMPM'));
		Institucion::create(array('nombre_institucion' => 'Registro de la Propiedad y Mercantil del Cantón La Troncal','siglas_institucion' => 'RPYMCLT'));
		Institucion::create(array('nombre_institucion' => 'Servicio de Acreditación Ecuatoriano','siglas_institucion' => 'SAE'));
		Institucion::create(array('nombre_institucion' => 'Servicio Aeropolicial','siglas_institucion' => 'SAP'));
		Institucion::create(array('nombre_institucion' => 'Empresa de Municiones Santa Bárbara','siglas_institucion' => 'SBEP'));
		Institucion::create(array('nombre_institucion' => 'Superintendencia de Bancos y Seguros','siglas_institucion' => 'SBS'));
		Institucion::create(array('nombre_institucion' => 'Servicio Ecuatoriano de Capacitación Profesional','siglas_institucion' => 'SECAP'));
		Institucion::create(array('nombre_institucion' => 'Servicio de Contratación de Obras','siglas_institucion' => 'SECOB'));
		Institucion::create(array('nombre_institucion' => 'Ministerio de Coordinación de los Sectores Estratégicos','siglas_institucion' => 'SE'));
		Institucion::create(array('nombre_institucion' => 'Servicio Nacional de Aduana del Ecuador','siglas_institucion' => 'SENAE'));
		Institucion::create(array('nombre_institucion' => 'Secretaría del Agua','siglas_institucion' => 'SENAGUA'));
		Institucion::create(array('nombre_institucion' => 'Secretaría de Educación Superior, Ciencia y Tecnología','siglas_institucion' => 'SENESCYT'));
		Institucion::create(array('nombre_institucion' => 'Secretaría Nacional de Planificación y Desarrollo','siglas_institucion' => 'SENPLADES'));
		Institucion::create(array('nombre_institucion' => 'Superintendencia de Economía Popular y Solidaria','siglas_institucion' => 'SEPS'));
		Institucion::create(array('nombre_institucion' => 'Servicio Nacional de Contratación Pública','siglas_institucion' => 'SERCOP'));
		Institucion::create(array('nombre_institucion' => 'Secretaría Técnica de Cooperación Internacional','siglas_institucion' => 'SETECI'));
		Institucion::create(array('nombre_institucion' => 'Secretaría Técnica del Sistema Nacional de Cualificaciones Profesionales','siglas_institucion' => 'SETEC'));
		Institucion::create(array('nombre_institucion' => 'Secretaría Técnica de Prevención Integral de Drogas','siglas_institucion' => 'SETED'));
		Institucion::create(array('nombre_institucion' => 'Secretaría Técnica de Juventudes','siglas_institucion' => 'SETEJU'));
		Institucion::create(array('nombre_institucion' => 'Secretaría de Gestión de Riesgos','siglas_institucion' => 'SGR'));
		Institucion::create(array('nombre_institucion' => 'Secretaría de Hidrocarburos','siglas_institucion' => 'SH'));
		Institucion::create(array('nombre_institucion' => 'Secretaría de Inteligencia','siglas_institucion' => 'SIN'));
		Institucion::create(array('nombre_institucion' => 'Servicio Integrado de Seguridad ECU 911','siglas_institucion' => 'SIS'));
		Institucion::create(array('nombre_institucion' => 'Secretaría Nacional de Comunicación','siglas_institucion' => 'SNC'));
		Institucion::create(array('nombre_institucion' => 'Secretaría Nacional de Gestión de la Política','siglas_institucion' => 'SNGP'));
		Institucion::create(array('nombre_institucion' => 'Servicio Nacional de Medicina Legal y Ciencias Forenses','siglas_institucion' => 'SNMLCF'));
		Institucion::create(array('nombre_institucion' => 'Servicio Público para Pago de Accidentes de Tránsito','siglas_institucion' => 'SPPAT'));
		Institucion::create(array('nombre_institucion' => 'Servicio de Protección Presidencial','siglas_institucion' => 'SPP'));
		Institucion::create(array('nombre_institucion' => 'Servicio de Rentas Internas','siglas_institucion' => 'SRI'));
		Institucion::create(array('nombre_institucion' => 'Secretaría Técnica del Comité Interinstitucional de Prevención de Asentamientos Irregulares','siglas_institucion' => 'STCPAHI'));
		Institucion::create(array('nombre_institucion' => 'Secretaría Técnica para la Gestión Inclusiva en Discapacidades','siglas_institucion' => 'STD'));
		Institucion::create(array('nombre_institucion' => 'Secretaría Técnica del Plan Toda una Vida','siglas_institucion' => 'STPTV'));
		Institucion::create(array('nombre_institucion' => 'Tame Línea Aérea del Ecuador EP','siglas_institucion' => 'TAME'));
		Institucion::create(array('nombre_institucion' => 'Tribunal Contencioso Electoral','siglas_institucion' => 'TCE'));
		Institucion::create(array('nombre_institucion' => 'Transportes Navieros Ecuatorianos   TRANSNAVE','siglas_institucion' => 'TNE'));
		Institucion::create(array('nombre_institucion' => 'Universidad Agraria del Ecuador','siglas_institucion' => 'UAE'));
		Institucion::create(array('nombre_institucion' => 'Unidad de Análisis Financiero y Económico','siglas_institucion' => 'UAFE'));
		Institucion::create(array('nombre_institucion' => 'Universidad Estatal Amazónica','siglas_institucion' => 'UEA'));
		Institucion::create(array('nombre_institucion' => 'Universidad Estatal de Bolívar','siglas_institucion' => 'UEB'));
		Institucion::create(array('nombre_institucion' => 'Empresa Pública La UEMPRENDE','siglas_institucion' => 'UEMPRENDE'));
		Institucion::create(array('nombre_institucion' => 'Unidad de Gestión y Ejecución de Derecho Público del Fideicomiso AGD  CFN no más Impunidad','siglas_institucion' => 'UGEDEP'));
		Institucion::create(array('nombre_institucion' => 'Empresa Pública Ingeniería, Materiales y Sistemas UGEP','siglas_institucion' => 'UGEP'));
		Institucion::create(array('nombre_institucion' => 'Universidad de Guayaquil','siglas_institucion' => 'UG'));
		Institucion::create(array('nombre_institucion' => 'Universidad de Investigación de Tecnología Experimental Yachay','siglas_institucion' => 'UITEY'));
		Institucion::create(array('nombre_institucion' => 'Empresa Pública Unidad Nacional de Almacenamiento UNA EP','siglas_institucion' => 'UNAEP'));
		Institucion::create(array('nombre_institucion' => 'Universidad Estatal de Milagro','siglas_institucion' => 'UNEMI'));
		Institucion::create(array('nombre_institucion' => 'Universidad Politécnica Estatal del Carchi','siglas_institucion' => 'UPEC'));
		Institucion::create(array('nombre_institucion' => 'Universidad Técnica Luis Vargas Torres de Esmeraldas','siglas_institucion' => 'UTELVT'));
		Institucion::create(array('nombre_institucion' => 'Universidad Técnica Estatal de Quevedo','siglas_institucion' => 'UTEQ'));
		Institucion::create(array('nombre_institucion' => 'Universidad Técnica de Manabí','siglas_institucion' => 'UTM'));
		Institucion::create(array('nombre_institucion' => 'Universidad Técnica del Norte','siglas_institucion' => 'UTN'));
		Institucion::create(array('nombre_institucion' => 'Vicepresidencia de la República','siglas_institucion' => 'VPR'));
		Institucion::create(array('nombre_institucion' => 'Vicepresidencia de la República','siglas_institucion' => 'VPR'));
		Institucion::create(array('nombre_institucion' => 'Gobierno Autonomos Descentralizado','siglas_institucion' => 'GAD'));
		Institucion::create(array('nombre_institucion' => 'Otras Funciones del Estado','siglas_institucion' => 'OFE'));
		Institucion::create(array('nombre_institucion' => 'Junta de Agua Potable','siglas_institucion' => 'JAP'));
		Institucion::create(array('nombre_institucion' => 'Junta de Agua Riego','siglas_institucion' => 'JAR'));


    }
}
